Repository badrobotics/FeRTOS, pull requests merged in 2020-05, with the labels that each got.

#56 Implement Basic Inter-process Communication
  examples/fertos_project/.cargo/config
  examples/fertos_project/.gitignore
  examples/fertos_project/.vscode/.cortex-debug.peripherals.state.json
  examples/fertos_project/.vscode/.cortex-debug.registers.state.json
  examples/fertos_project/.vscode/launch.json
  examples/fertos_project/.vscode/tasks.json
  examples/fertos_project/Cargo.toml
  examples/fertos_project/build.rs
  examples/fertos_project/link_123.x
  examples/fertos_project/link_1294.x
  examples/fertos_project/openocd.cfg
  examples/fertos_project/openocd.gdb
  examples/fertos_project/src/cmd.rs
  examples/fertos_project/src/main.rs
  examples/fertos_project/src/stdio.rs
  examples/fertos_project/src/uart_server.rs
  examples/qemu_project/qemu.gdb
  examples/qemu_project/src/main.rs
  fe_osi/Cargo.toml
  fe_osi/src/allocator.rs
  fe_osi/src/arm.s
  fe_osi/src/ipc.rs
  fe_osi/src/lib.rs
  fe_rtos/Cargo.toml
  fe_rtos/src/arm_syscall.s
  fe_rtos/src/fe_alloc.rs
  fe_rtos/src/ipc/mod.rs
  fe_rtos/src/ipc/subscriber.rs
  fe_rtos/src/ipc/topic.rs
  fe_rtos/src/lib.rs
  fe_rtos/src/syscall.rs
  fe_rtos/src/task/mod.rs
Labels: enhancement

#73 Update Cargo toml files
  Cargo.toml
  fe_osi/Cargo.toml
  fe_rtos/Cargo.toml
Labels: Documentation, FeOSI, FeRTOS

#74 Free a task's dynamically allocated memory when it exits
  examples/qemu_project/src/main.rs
  fe_rtos/src/fe_alloc.rs
  fe_rtos/src/task/mod.rs
Labels: FeRTOS, Improvement

#72 add static anaysis jobs to ci
  .github/workflows/build.yml
  .github/workflows/static_analysis.yml
Labels: CI, FeOSI, FeRTOS, Improvement
